# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S terraform Azure!
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client-secret=$(client_secret) -var ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxlndqS7+I3tftXHqFw5t19A+CLVBpIOBr6RcuVyd+Y6JqHs/9EX1HoGNWUTjnH/w068weiqBC4WPKHelWyomkdloqy26UeACdJ+And8jNA7yXHpTbXeHBQ3T33xPQuy2LDDyUt0M1ESHMISxSXJwYC0x6bbXiwNsm0J4IIFHcK9pFvT3siKt0VxB995Nz+piBM29pdD1FgwsINwVVdE6uhuPBGe4/4+SP6DE9+bhGczOTjFQcE9EW89v2s0dI1UHIoQkuyWfwHyT3+Vv2fCWKVfpTf5gnWJZ/0bfZF0j2HUeawotYvV11lsno6+PH7VQhxOr/WqinQHRn9jS5C6LLMSs660WGaWNG8Vi1k/d6cIbUsxRqylsxrY2mLQHkICx1dtr6GlMQjsJyDwK6lWT4OkTjgULAZuK9gIl/d5r30rFQd/gfeAd1hVTYAIyny1Pty5ifx1yxs3uoNlzbThP5WiduLnxndro8sf1Bh1isjgIoWB4YbDfHd1Wqdtgf9LyIU8ADN72bdsE8VKsG/UR1Nvx3iDR/0Rx65EIoJgM26MHq/reW8AArmG2vEwNKFn+ltnsY38+y99ceVyC4rStwJoFdxiD6C7sJVOXK1aMtZmL2GB1GCvKjPC/38r+lCaH2f26/+7rxibJnqB+2tpb8JOBEjLMmrqU4LvcCAU1NRQ== Lenovo@DESKTOP-28T9K5N"'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctravikumarxyz'
    backendAzureRmContainerName: 'storageacctravikumarcontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'


    