apiVersion: v1
kind: Service
metadata:
    name: "in28minutescluster-29f3"
    labels:
        app: "in28minutescluster-29f3"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "in28minutescluster-29f3"